# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

def merchant_data

  [{:id=>"1", :type=>"merchant", :attributes=>{:name=>"Schroeder-Jerde"}},
   {:id=>"2", :type=>"merchant", :attributes=>{:name=>"Klein, Rempel and Jones"}},
   {:id=>"3", :type=>"merchant", :attributes=>{:name=>"Willms and Sons"}},
   {:id=>"4", :type=>"merchant", :attributes=>{:name=>"Cummings-Thiel"}},
   {:id=>"5", :type=>"merchant", :attributes=>{:name=>"Williamson Group"}},
   {:id=>"6", :type=>"merchant", :attributes=>{:name=>"Williamson Group"}},
   {:id=>"7", :type=>"merchant", :attributes=>{:name=>"Bernhard-Johns"}},
   {:id=>"8", :type=>"merchant", :attributes=>{:name=>"Osinski, Pollich and Koelpin"}},
   {:id=>"9", :type=>"merchant", :attributes=>{:name=>"Hand-Spencer"}},
   {:id=>"10", :type=>"merchant", :attributes=>{:name=>"Bechtelar, Jones and Stokes"}},
   {:id=>"11", :type=>"merchant", :attributes=>{:name=>"Pollich and Sons"}},
   {:id=>"12", :type=>"merchant", :attributes=>{:name=>"Kozey Group"}},
   {:id=>"13", :type=>"merchant", :attributes=>{:name=>"Tillman Group"}},
   {:id=>"14", :type=>"merchant", :attributes=>{:name=>"Dicki-Bednar"}},
   {:id=>"15", :type=>"merchant", :attributes=>{:name=>"Adams-Kovacek"}},
   {:id=>"16", :type=>"merchant", :attributes=>{:name=>"Bosco, Howe and Davis"}},
   {:id=>"17", :type=>"merchant", :attributes=>{:name=>"Ullrich-Moen"}},
   {:id=>"18", :type=>"merchant", :attributes=>{:name=>"Koepp LLC"}},
   {:id=>"19", :type=>"merchant", :attributes=>{:name=>"Brown Inc"}},
   {:id=>"20", :type=>"merchant", :attributes=>{:name=>"Schulist, Wilkinson and Leannon"}},
   {:id=>"21", :type=>"merchant", :attributes=>{:name=>"Leffler, Rice and Leuschke"}},
   {:id=>"22", :type=>"merchant", :attributes=>{:name=>"Thiel Inc"}},
   {:id=>"23", :type=>"merchant", :attributes=>{:name=>"Kilback Inc"}},
   {:id=>"24", :type=>"merchant", :attributes=>{:name=>"Ferry and Sons"}},
   {:id=>"25", :type=>"merchant", :attributes=>{:name=>"Hickle-Hessel"}},
   {:id=>"26", :type=>"merchant", :attributes=>{:name=>"Balistreri, Schaefer and Kshlerin"}},
   {:id=>"27", :type=>"merchant", :attributes=>{:name=>"Shields, Hirthe and Smith"}},
   {:id=>"28", :type=>"merchant", :attributes=>{:name=>"Schiller, Barrows and Parker"}},
   {:id=>"29", :type=>"merchant", :attributes=>{:name=>"Tromp Inc"}},
   {:id=>"30", :type=>"merchant", :attributes=>{:name=>"Ernser, Borer and Marks"}},
   {:id=>"31", :type=>"merchant", :attributes=>{:name=>"Maggio LLC"}},
   {:id=>"32", :type=>"merchant", :attributes=>{:name=>"Rowe and Sons"}},
   {:id=>"33", :type=>"merchant", :attributes=>{:name=>"Quitzon and Sons"}},
   {:id=>"34", :type=>"merchant", :attributes=>{:name=>"Rutherford, Bogan and Leannon"}},
   {:id=>"35", :type=>"merchant", :attributes=>{:name=>"Schuster Group"}},
   {:id=>"36", :type=>"merchant", :attributes=>{:name=>"Bernhard, Stanton and Funk"}},
   {:id=>"37", :type=>"merchant", :attributes=>{:name=>"Dibbert Group"}},
   {:id=>"38", :type=>"merchant", :attributes=>{:name=>"Johnston, Gleason and O'Keefe"}},
   {:id=>"39", :type=>"merchant", :attributes=>{:name=>"Schuppe, Friesen and Schmeler"}},
   {:id=>"40", :type=>"merchant", :attributes=>{:name=>"Wilderman Group"}},
   {:id=>"41", :type=>"merchant", :attributes=>{:name=>"Crona LLC"}},
   {:id=>"43", :type=>"merchant", :attributes=>{:name=>"Marks, Shanahan and Bauch"}},
   {:id=>"44", :type=>"merchant", :attributes=>{:name=>"Gibson Group"}},
   {:id=>"45", :type=>"merchant", :attributes=>{:name=>"Dickinson-Klein"}},
   {:id=>"46", :type=>"merchant", :attributes=>{:name=>"Huels, Homenick and Smith"}},
   {:id=>"47", :type=>"merchant", :attributes=>{:name=>"Franecki-Ullrich"}},
   {:id=>"48", :type=>"merchant", :attributes=>{:name=>"Hand, Boyer and Mitchell"}},
   {:id=>"49", :type=>"merchant", :attributes=>{:name=>"Marvin, Renner and Bauch"}},
   {:id=>"50", :type=>"merchant", :attributes=>{:name=>"Nader-Hyatt"}},
   {:id=>"51", :type=>"merchant", :attributes=>{:name=>"Paucek Inc"}},
   {:id=>"52", :type=>"merchant", :attributes=>{:name=>"Reynolds Inc"}},
   {:id=>"53", :type=>"merchant", :attributes=>{:name=>"Rath, Gleason and Spencer"}},
   {:id=>"54", :type=>"merchant", :attributes=>{:name=>"Zemlak-Collins"}},
   {:id=>"55", :type=>"merchant", :attributes=>{:name=>"Koch, Wolf and Jerde"}},
   {:id=>"56", :type=>"merchant", :attributes=>{:name=>"Sporer, Christiansen and Connelly"}},
   {:id=>"57", :type=>"merchant", :attributes=>{:name=>"Parisian Group"}},
   {:id=>"58", :type=>"merchant", :attributes=>{:name=>"Rogahn LLC"}},
   {:id=>"59", :type=>"merchant", :attributes=>{:name=>"Pollich, Romaguera and Bayer"}},
   {:id=>"60", :type=>"merchant", :attributes=>{:name=>"Smitham LLC"}},
   {:id=>"61", :type=>"merchant", :attributes=>{:name=>"Auer, Crooks and Shanahan"}},
   {:id=>"62", :type=>"merchant", :attributes=>{:name=>"Kunze, Kautzer and Little"}},
   {:id=>"63", :type=>"merchant", :attributes=>{:name=>"Lehner, Padberg and O'Hara"}},
   {:id=>"64", :type=>"merchant", :attributes=>{:name=>"Koepp, Waelchi and Donnelly"}},
   {:id=>"65", :type=>"merchant", :attributes=>{:name=>"Hermann, Weimann and Botsford"}},
   {:id=>"66", :type=>"merchant", :attributes=>{:name=>"Bechtelar LLC"}},
   {:id=>"67", :type=>"merchant", :attributes=>{:name=>"Torp and Sons"}},
   {:id=>"68", :type=>"merchant", :attributes=>{:name=>"Heaney Group"}},
   {:id=>"69", :type=>"merchant", :attributes=>{:name=>"Watsica-Parisian"}},
   {:id=>"70", :type=>"merchant", :attributes=>{:name=>"Weimann-Schimmel"}},
   {:id=>"71", :type=>"merchant", :attributes=>{:name=>"Schulist Group"}},
   {:id=>"72", :type=>"merchant", :attributes=>{:name=>"Greenfelder-Keebler"}},
   {:id=>"73", :type=>"merchant", :attributes=>{:name=>"Sipes LLC"}},
   {:id=>"74", :type=>"merchant", :attributes=>{:name=>"Daugherty Group"}},
   {:id=>"75", :type=>"merchant", :attributes=>{:name=>"Eichmann-Turcotte"}},
   {:id=>"76", :type=>"merchant", :attributes=>{:name=>"Kirlin, Jakubowski and Smitham"}},
   {:id=>"77", :type=>"merchant", :attributes=>{:name=>"Kutch, Blick and O'Keefe"}},
   {:id=>"78", :type=>"merchant", :attributes=>{:name=>"Heathcote-Hettinger"}},
   {:id=>"79", :type=>"merchant", :attributes=>{:name=>"Pacocha-Mayer"}},
   {:id=>"80", :type=>"merchant", :attributes=>{:name=>"Jakubowski, Predovic and Hudson"}},
   {:id=>"81", :type=>"merchant", :attributes=>{:name=>"Jewess Group"}},
   {:id=>"82", :type=>"merchant", :attributes=>{:name=>"Kulas LLC"}},
   {:id=>"83", :type=>"merchant", :attributes=>{:name=>"Gulgowski, Torphy and Lynch"}},
   {:id=>"84", :type=>"merchant", :attributes=>{:name=>"Terry-Moore"}},
   {:id=>"85", :type=>"merchant", :attributes=>{:name=>"Sauer and Sons"}},
   {:id=>"86", :type=>"merchant", :attributes=>{:name=>"Marvin Group"}},
   {:id=>"87", :type=>"merchant", :attributes=>{:name=>"Johnson-Wiza"}},
   {:id=>"88", :type=>"merchant", :attributes=>{:name=>"Kiehn Group"}},
   {:id=>"89", :type=>"merchant", :attributes=>{:name=>"Kassulke, O'Hara and Quitzon"}},
   {:id=>"90", :type=>"merchant", :attributes=>{:name=>"Friesen, Hackett and Runte"}},
   {:id=>"91", :type=>"merchant", :attributes=>{:name=>"Weissnat, Hermiston and Beer"}},
   {:id=>"92", :type=>"merchant", :attributes=>{:name=>"Zemlak, Volkman and Haley"}},
   {:id=>"93", :type=>"merchant", :attributes=>{:name=>"Walter-Schowalter"}},
   {:id=>"94", :type=>"merchant", :attributes=>{:name=>"Boehm LLC"}},
   {:id=>"95", :type=>"merchant", :attributes=>{:name=>"Johnson-Dickinson"}},
   {:id=>"96", :type=>"merchant", :attributes=>{:name=>"Swaniawski-Cremin"}},
   {:id=>"97", :type=>"merchant", :attributes=>{:name=>"Rice, Jerde and White"}},
   {:id=>"98", :type=>"merchant", :attributes=>{:name=>"Okuneva, Prohaska and Rolfson"}},
   {:id=>"100", :type=>"merchant", :attributes=>{:name=>"Wisozk, Hoeger and Bosco"}}
 ]

end
